properties:
  plan: 1
  basePath: ${BASE_PATH}
  croquis: ${CROQUIS}
  controlPoint: ${CONTROL_POINT}
  slash: ${SLASH}

management.endpoints.web.exposure.include: "*"

#server:
#  servlet.contextPath: /
#  port: 8080
#  max-http-header-size: 64KB
server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/misbarrancosbdesarrollo.com/keystore.p12
    key-store-password: "Luis884994"
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  config.name: canyoningApp
  jackson.serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  profiles.active: local
  mail:
    host: smtp.ionos.es
    port: 465
    username: documentos@misbarrancosbdesarrollo.com #canyoningApp@hotmail.com
    password: ${PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
springdoc:
  api-docs:
    enabled: false
    path: /openapi/canyoningApp-openapi.json
  swagger-ui:
    enabled: false
    operationsSorter: alpha
    path: /swagger-ui.html
    tagsSorter: alpha
    url: /openapi/canyoningApp-openapi.yml